<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="deg_to_rad" value="0.017453293" />

  <!-- The inertia for the MiR platform is intentionally chosen to be smaller than
       the bounding box and also shifted a bit to the back, because most of the mass
       is in the lower center back (because of the batteries). -->
  <xacro:property name="mir_base_inertial_x" value="0" />
  <xacro:property name="mir_base_inertial_y" value="0.0" />
  <xacro:property name="mir_base_inertial_z" value="0.15" />
  <xacro:property name="mir_base_inertial_x_length" value="0.80" />
  <xacro:property name="mir_base_inertial_y_length" value="0.58" />
  <xacro:property name="mir_base_inertial_z_length" value="0.30" />

  <xacro:property name="mir_base_mass" value="97.0" />
  <xacro:property name="mir_act_wheel_radius" value="0.100" />
  <xacro:property name="mir_act_wheel_width" value="0.038" />
  <xacro:property name="mir_act_wheel_mass" value="1.0" />
  <xacro:property name="mir_act_wheel_dx" value="-0.004485" />
  <xacro:property name="mir_act_wheel_dy" value="0.2015" />

  <xacro:property name="mir_caster_wheel_radius" value="0.0625" />
  <xacro:property name="mir_caster_wheel_width" value="0.032" />
  <xacro:property name="mir_caster_wheel_mass" value="1.0" />
  <xacro:property name="mir_caster_wheel_dx" value="-0.0382" />
  <xacro:property name="mir_caster_wheel_dy" value="0" />
  <xacro:property name="mir_caster_wheel_dz" value="-0.094" />
  <xacro:property name="mir_front_caster_wheel_base_dx" value="0.3037" />
  
  <xacro:property name="mir_back_caster_wheel_base_dx"  value="0.296" />
  <xacro:property name="mir_caster_wheel_base_dy" value="0.188" />

  <xacro:property name="mir_caster_wheel_base_dz" value="${mir_caster_wheel_radius - mir_caster_wheel_dz}" />

  <xacro:macro name="actuated_wheel" params="prefix locationprefix locationright">
    <joint name="${prefix}${locationprefix}_wheel_joint" type="continuous">
      <origin xyz="0.0 ${-mir_act_wheel_dy * locationright} ${mir_act_wheel_radius}" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}${locationprefix}_wheel_link" />
      <axis xyz="0 1 0" />
      <limit effort="100" velocity="20.0" />
    </joint>

    <link name="${prefix}${locationprefix}_wheel_link">
      <xacro:cylinder_inertial mass="${mir_act_wheel_mass}" radius="${mir_act_wheel_radius}" length="${mir_act_wheel_width}">
        <origin xyz="0 0 0" rpy="0 0 0" /> <!-- ${0.5 * pi} 0 0 -->
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${mir_act_wheel_radius}" length="${mir_act_wheel_width}" />
        </geometry>
        <xacro:insert_block name="material_black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${mir_act_wheel_radius}" length="${mir_act_wheel_width}" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}${locationprefix}_wheel_link">
      <material>Gazebo/FlatBlack</material>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="caster_wheel" params="prefix locationprefix locationright wheel_base_dx">
    <!-- caster hub -->
    <joint name="${prefix}${locationprefix}_caster_rotation_joint" type="continuous">
      <origin xyz="${wheel_base_dx} ${-mir_caster_wheel_base_dy * locationright} ${mir_caster_wheel_base_dz}" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}${locationprefix}_caster_rotation_link" />
      <axis xyz="0 0 1" />
      <dynamics damping="0.01" friction="0.0"/>
    </joint>

    <link name="${prefix}${locationprefix}_caster_rotation_link">
      <inertial>
        <!-- <origin xyz="0 0 -0.042500000044" rpy="${0.5 * pi} ${24 * deg_to_rad} ${1.5 * pi}" /> -->
        <origin xyz="0 0 -0.042500000044" rpy="0 0 0" /> <!-- ${24 * deg_to_rad} 0 ${0.5 * pi} -->
        <mass value="0.3097539019" />
        <inertia
          ixx="0.0005844517978"
          ixy="0"
          ixz="0"
          iyy="0.00052872551237"
          iyz="0"
          izz="0.00017923555074" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://relax_urdf/meshes/caster_wheel_base.stl" />
        </geometry>
        <xacro:insert_block name="material_black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://relax_urdf/meshes/caster_wheel_base.stl" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}${locationprefix}_caster_rotation_link">
    <material>Gazebo/FlatBlack</material>
    </gazebo>

    <!-- caster wheel -->
    <joint name="${prefix}${locationprefix}_caster_wheel_joint" type="continuous">
      <origin xyz="${mir_caster_wheel_dx} ${-mir_caster_wheel_dy * locationright} ${mir_caster_wheel_dz}" rpy="0 0 0" />
      <parent link="${prefix}${locationprefix}_caster_rotation_link" />
      <child link="${prefix}${locationprefix}_caster_wheel_link" />
      <axis xyz="0 1 0" />
    </joint>

    <link name="${prefix}${locationprefix}_caster_wheel_link">
      <xacro:cylinder_inertial mass="${mir_caster_wheel_mass}" radius="${mir_caster_wheel_radius}" length="${mir_caster_wheel_width}">
        <origin xyz="0 0 0" rpy="0 0 0" /> <!--${0.5 * pi} -->
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" /> <!--${pi/2} 0 0 -->
        <geometry>
          <cylinder radius="${mir_caster_wheel_radius}" length="${mir_caster_wheel_width}" />
        </geometry>
        <xacro:insert_block name="material_black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" /> <!--${pi/2} 0 0 -->
        <geometry>
          <cylinder radius="${mir_caster_wheel_radius}" length="${mir_caster_wheel_width}" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}${locationprefix}_caster_wheel_link">
      <material>Gazebo/FlatBlack</material>
    </gazebo>
  </xacro:macro>
</robot>
