solver_options:
    regularization: 1e-4
    back_end: "qpoases"

stack:
    - ["Base"]
    
constraints: ["JointLimits", "VelocityLimits"]

JointLimits:
    type: "JointLimits"

VelocityLimits:
    type: "VelocityLimits"


Base:
    type: "Cartesian"
    name: "mir_control"
    distal_link: "base_link"
    indices: [0, 5]
    lambda: 0.1
    name: mir

